### ISSUE TITLE
Refactor [modules/feds.py] and [modules/sql/feds_sql.py]

### ISSUE THREAD

**Issue by SoapDev2018** [MetaButler/MetaButler#1]
**Goal:** Perform code refactoring of [[modules/feds.py](https://github.com/DESTROYER-32/MetaButler/blob/main/MetaButler/modules/feds.py)] and [[modules/sql/feds_sql.py](https://github.com/DESTROYER-32/MetaButler/blob/main/MetaButler/modules/sql/feds_sql.py)]
**Mission:** Improve code quality, reduce stale code smell

Right now there is a lot of duplication in the code, lots of unused variables. Current goal is to remove unused variables as much as possible, cleanup stale and smelly code and eventually rewrite some code logic to reduce cognitive complexity.

**Comment by iamajneya** [comment]
@SoapDev2018
